In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [2]:
crop_df=pd.read_csv("datasets/Crop_recommendation.csv")

In [3]:
crop_df.head()

    N   P   K  temperature   humidity        ph    rainfall label
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice
3  74  35  40    26.491096  80.158363  6.980401  242.864034  rice
4  78  42  42    20.130175  81.604873  7.628473  262.717340  rice

In [4]:
crop_df[crop_df.isnull().any(axis=1)]

Empty DataFrame
Columns: [N, P, K, temperature, humidity, ph, rainfall, label]
Index: []

In [5]:
crop_df.duplicated().any()

np.False_

In [6]:
len(crop_df)

2200

In [7]:
crop_df=crop_df.drop_duplicates()

In [8]:
len(crop_df)

2200

In [9]:
numeric_cols = crop_df.select_dtypes(include=[np.number]).columns
outlier_summary = {}
for col in numeric_cols:
    Q1 = crop_df[col].quantile(0.25)
    Q3 = crop_df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    outliers = crop_df[(crop_df[col] < lower_bound) | (crop_df[col] > upper_bound)][col]
    outlier_summary[col] = {
        "Lower Bound": lower_bound,
        "Upper Bound": upper_bound,
        "Outlier Count": outliers.shape[0],
        "Outlier Values": outliers.values
    }
for col, info in outlier_summary.items():
    print("\nColumn:", col)
    print("Lower Bound:", info["Lower Bound"])
    print("Upper Bound:", info["Upper Bound"])
    print("Outliers:", info["Outlier Values"])
    print("Count:", info["Outlier Count"])

Column: N
Lower Bound: -73.875
Upper Bound: 179.125
Outliers: []
Count: 0

Column: P
Lower Bound: -32.0
Upper Bound: 128.0
Outliers: [130 144 131 140 134 130 145 139 141 138 144 136 136 145 132 133 140 132
 142 135 139 141 142 129 134 138 131 132 137 136 134 139 138 142 133 139
 134 140 139 136 139 133 130 135 140 132 132 142 140 133 135 145 136 129
 130 129 135 132 140 145 139 144 141 138 138 143 142 134 144 129 137 139
 144 139 133 143 140 137 144 143 140 144 141 144 143 137 144 143 141 142
 138 137 135 144 133 130 143 143 139 136 131 140 138 145 139 136 138 136
 134 143 145 141 136 136 141 129 138 137 132 139 143 144 143 135 130 142
 129 135 145 131 140 138 140 145 132 137 144 140]
Count: 138

Column: K
Lower Bound: -23.5
Upper Bound: 92.5
Outliers: [195 204 205 196 196 198 197 195 203 204 197 205 201 203 204 195 202 205
 197 204 201 197 198 201 199 205 203 197 200 197 203 203 198 202 196 201
 199 204 198 204 201 204 197 195 200 197 200 201 196 203 204 203 195 199
 202 195 202 195 201 195 203 201 196 205 195 196 199 202 203 199 205 196
 202 199 199 201 195 201 203 203 205 204 200 203 202 200 199 196 197 197
 198 203 204 197 204 200 201 202 195 204 196 197 205 201 201 204 205 205
 196 199 197 196 204 199 200 199 198 199 203 195 205 198 196 198 204 203
 197 198 200 198 196 203 197 201 202 195 204 196 202 202 201 196 198 205
 205 199 198 200 204 202 196 202 198 200 199 197 201 204 203 205 195 202
 200 200 196 205 197 200 205 197 204 195 204 195 201 197 200 204 197 203
 204 196 197 203 196 203 205 203 205 201 203 195 198 197 195 197 198 196
 196 197]
Count: 200

Column: temperature
Lower Bound: 14.080955682499999
Upper Bound: 37.2500728825
Outliers: [37.46566825 39.64851881 12.14190714 12.7567962  39.04071989 39.70772192
  9.46796044  8.82567475 11.02105378 12.087022   12.80000387 38.06099482
 39.06555518 10.89875873 11.7976469  11.36300891 41.18664903 10.38004759
 10.72302459 41.20733624 40.66012294 11.82768186 13.28504331 39.37102553
 41.65602996 41.36106301 41.94865736 11.18994268 13.05809741  9.72445761
  9.53558554 13.42988625  9.85124263  9.94992908 13.36050601 11.50322938
 12.22816189 10.01081312 10.78689755 11.89925671 13.8377282  11.54785707
 13.70319166 13.20844373 12.59093977 11.86631922 11.03367937 10.2708877
 10.35609594 10.16431299 11.69894639 42.39413392 38.4191628  42.92325255
 40.21199348 42.13473976 38.4418717  39.01793345 38.72382798 43.30204933
 40.78881819 39.30050027 39.73149053 39.23342464 40.76998685 42.30495821
 42.84609252 43.67549305 42.07213781 41.41968393 42.54744013 43.08022702
 41.04224355 42.93368602 43.36051537 43.03714283 37.4620912  38.73218907
 38.38231475 42.93605359 37.58899717 40.00439101 38.2016825  40.10207731
 38.58954491 41.31330062]
Count: 86

Column: humidity
Lower Bound: 15.731725873750001
Upper Bound: 134.47899768374998
Outliers: [15.40589717 15.65809214 15.40312102 15.22538951 14.69765308 14.71070537
 14.32313811 15.11279612 14.99927489 14.42457525 14.25803981 15.21618225
 14.27327988 14.92241479 15.15405941 15.48083156 14.70085967 14.99451145
 14.72115044 14.44228303 14.2804191  14.44008871 14.76014523 14.82633099
 14.74071856 15.57324389 15.27824066 14.33847406 14.77959596 15.36143547]
Count: 30

Column: ph
Lower Bound: 4.543768066249998
Upper Bound: 8.351567354250005
Outliers: [8.75379533 8.71819285 8.49012714 8.51997575 8.82927333 8.62166298
 8.86874144 8.76612865 8.7363379  8.38018527 8.4238737  8.71996089
 8.86147967 3.6928636  4.37174558 8.39913596 8.84065626 9.67924087
 8.98534819 4.52417156 9.92621229 3.71105919 9.25408944 3.80842917
 4.52363558 3.51040431 3.82803146 8.86953282 3.79357518 4.19318912
 9.39269461 4.51615406 8.62010754 9.45949344 9.16069175 9.07201141
 3.50475231 8.66077954 3.55882283 9.41600311 8.9230957  8.70929169
 4.39769881 8.53207873 3.5253661  8.86979671 9.40688753 8.35495812
 8.63492974 9.11277168 9.93509073 8.91407489 8.6395862  8.62151407
 3.53200867 4.50752355 4.52572233]
Count: 57

Column: rainfall
Lower Bound: -25.022046700000033
Upper Bound: 213.84124050000003
Outliers: [226.6555374 263.9642476 242.8640342 262.7173405 251.0549998 271.3248604
 241.9741949 230.4462359 221.2091958 264.6148697 250.0832336 284.4364567
 231.0863347 276.6552459 224.5550169 291.2986618 231.3843163 233.1075816
 224.0581164 257.0038865 271.3586137 260.2634026 240.0810647 272.2017204
 224.6757231 270.4417274 233.1321372 272.2999056 285.2493645 298.4018471
 257.0343554 248.7183228 298.5601175 265.5355937 233.0453455 253.7202781
 219.9048349 227.3637009 286.5083725 283.9338466 217.3788583 267.9761948
 277.9626192 245.1511304 245.6626799 279.5451717 263.6372176 243.5120414
 263.1103304 269.5039162 260.8875056 295.6094492 257.4914906 278.0791793
 280.4044392 223.3671883 220.1156708 231.7364957 242.3170629 233.7034975
 230.2242223 290.6793783 241.2013513 218.9163567 248.2256491 256.9964761
 295.9248796 287.5766935 243.0745066 235.6133585 232.7046126 238.5008779
 248.8592986 218.2299187 214.4103848 246.3613268 231.5153161 218.142147
 234.8466111 241.8202079 240.4795923 234.496633  218.0908814 240.6863901
 239.7427554 224.5903664 224.3206759 215.9195049 218.0055713 218.5241851
 218.080385  224.7006953 214.4128874 222.803013  224.4016682 215.1968037
 224.8315729 213.9011021 225.6323656 221.2258168]
Count: 100

In [10]:
df_clean = crop_df.copy()

for col in numeric_cols:
    Q1 = df_clean[col].quantile(0.25)
    Q3 = df_clean[col].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    df_clean = df_clean[(df_clean[col] >= lower_bound) & (df_clean[col] <= upper_bound)]

In [11]:
df_clean.head()

    N   P   K  temperature   humidity        ph    rainfall label
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
3  74  35  40    26.491096  80.158363  6.980401  242.864034  rice
7  94  53  40    20.277744  82.894086  5.718627  241.974195  rice
8  89  54  38    24.515881  83.535216  6.685346  230.446236  rice

In [12]:
df_clean['label'].unique()

array(['rice', 'maize', 'chickpea', 'kidneybeans', 'pigeonpeas',
       'mothbeans', 'mungbean', 'blackgram', 'lentil', 'pomegranate',
       'banana', 'mango', 'watermelon', 'muskmelon', 'orange', 'papaya',
       'coconut', 'cotton', 'jute', 'coffee'], dtype=object)

In [13]:
len(df_clean)

1846

In [14]:
encoder=LabelEncoder()

In [15]:
df_clean['Crops']=encoder.fit_transform(df_clean['label'])

In [16]:
df_clean.head()

    N   P   K  temperature   humidity        ph    rainfall label  Crops
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice     18
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice     18
3  74  35  40    26.491096  80.158363  6.980401  242.864034  rice     18
7  94  53  40    20.277744  82.894086  5.718627  241.974195  rice     18
8  89  54  38    24.515881  83.535216  6.685346  230.446236  rice     18

In [17]:
df_clean=df_clean.drop(columns=['label'])

In [18]:
X=df_clean.drop(columns=['Crops'])
y=df_clean['Crops']

In [19]:
X.head()

    N   P   K  temperature   humidity        ph    rainfall
0  90  42  43    20.879744  82.002744  6.502985  202.935536
1  85  58  41    21.770462  80.319644  7.038096  226.655537
3  74  35  40    26.491096  80.158363  6.980401  242.864034
7  94  53  40    20.277744  82.894086  5.718627  241.974195
8  89  54  38    24.515881  83.535216  6.685346  230.446236

In [20]:
y

0       18
1       18
3       18
7       18
8       18
        ..
2195     4
2196     4
2197     4
2198     4
2199     4
Name: Crops, Length: 1846, dtype: int64

In [21]:
scaler=StandardScaler()

In [22]:
X_scaler=scaler.fit_transform(X)

In [23]:
X_scaler

array([[ 0.94386616, -0.14050707,  0.6173409 , ...,  0.54021372,
         0.0141572 ,  1.93559816],
       [ 0.81200377,  0.57059932,  0.49693187, ...,  0.46588231,
         0.80095938,  2.38811036],
       [ 0.5219065 , -0.45161612,  0.43672735, ...,  0.45875957,
         0.7161267 ,  2.69732378],
       ...,
       [ 1.68229557, -0.54050442, -0.16531782, ..., -0.11241614,
        -0.19224719,  1.37066955],
       [ 1.65592309, -0.58494857,  0.07550025, ..., -0.77918307,
         0.39028418,  0.49030165],
       [ 1.31308086, -1.20716667, -0.16531782, ..., -0.41399243,
         0.4212205 ,  0.75283786]], shape=(1846, 7))

In [24]:
X_train,X_test,y_train,y_test=train_test_split(X_scaler,y,random_state=32,test_size=0.25)

In [25]:
classfier=RandomForestClassifier()

In [26]:
classfier.fit(X_train,y_train)

RandomForestClassifier()

In [27]:
classfier.score(X_train,y_train)

1.0

In [28]:
training_prediction=classfier.predict(X_train)
testing_prediction=classfier.predict(X_test)

In [29]:
Training_accuracy=accuracy_score(y_pred=training_prediction,y_true=y_train)
Testing_accuracy=accuracy_score(y_pred=testing_prediction,y_true=y_test)

In [30]:
print("training accuracy=",Training_accuracy," testing accuracy=",Testing_accuracy)

training accuracy= 1.0  testing accuracy= 0.9913419913419913

In [31]:
import pickle
with open("models/model.pkl","wb") as m:
    pickle.dump(classfier,m)
with open("models/encoder.pkl","wb") as e:
    pickle.dump(encoder,e)
with open("models/scaler.pkl","wb") as s:
    pickle.dump(scaler,s)